const STORAGE = { profiles: 'bloodcare-profiles', history: 'bloodcare-history', theme: 'bloodcare-theme', language: 'bloodcare-language' };
const state = { profiles: [], history: [], theme: localStorage.getItem(STORAGE.theme) || 'dark', language: localStorage.getItem(STORAGE.language) || 'en' };
const copy = {
  en: { app_jargon: 'Guard Your Heart Health', footer_text: '♥ Track daily, live healthy. Made with care for your heart.', nav_create_acc: 'Create Account', nav_edit_acc: 'Edit Account', nav_history: 'History', nav_theme: 'Theme', nav_language: 'Language', btn_check: 'Check Now', lbl_systolic: 'Systolic (mmHg)', lbl_diastolic: 'Diastolic (mmHg)', lbl_pulse: 'Pulse (BPM) [Optional]', lbl_account: 'Select Profile [Optional]' },
  id: { app_jargon: 'Jaga Kesehatan Jantung Anda', footer_text: '♥ Pantau harian, hidup sehat. Dibuat dengan kepedulian untuk jantung Anda.', nav_create_acc: 'Buat Akun', nav_edit_acc: 'Edit Akun', nav_history: 'Riwayat', nav_theme: 'Tema', nav_language: 'Bahasa', btn_check: 'Cek Sekarang', lbl_systolic: 'Sistolik (mmHg)', lbl_diastolic: 'Diastolik (mmHg)', lbl_pulse: 'Denyut Nadi (BPM) [Opsional]', lbl_account: 'Pilih Profil [Opsional]' }
};
const messages = {
  normal: ['Cakep! Tekanan darahmu stabil banget. Pertahankan pola hidup sehatmu, ya!', 'Wah, jantungmu lagi seneng nih. Tetap rileks dan jaga makan!', 'Perfect score! Tekanan darah normal, kamu siap jalani hari dengan maksimal.'],
  elevated: ['Hmm, agak naik sedikit nih. Kurangi begadang dan minum air putih yang cukup ya.', 'Lampu kuning! Perhatikan asupan garam dan sempatkan jalan kaki santai.', 'Sedikit di atas normal. Jangan lupa rehat sebentar kalau lagi banyak pikiran.'],
  high: ['Tekanan darahmu lagi tinggi. Kurangi stres, tarik napas dalam, dan pertimbangkan untuk konsultasi.', 'Whoa, angka ini butuh perhatian. Kurangi garam ekstra dan jangan lupa istirahat yang benar!', 'Waktunya slow down. Jaga pola makan dan periksakan ke dokter jika terus menerus tinggi.']
};
const categories = { normal: { label: 'Normal', color: '#72e2a4', title: 'Looking good!' }, elevated: { label: 'Elevated', color: '#ffd166', title: 'A little nudge today.' }, stage1: { label: 'Hypertension Stage 1', color: '#ff9f43', title: 'Let’s give this some attention.' }, stage2: { label: 'Hypertension Stage 2', color: '#ff6b6b', title: 'Time to slow down.' }, crisis: { label: 'Hypertensive Crisis', color: '#d94b75', title: 'Please seek care now.' } };
const $ = (selector) => document.querySelector(selector);
function read(key, fallback) { try { return JSON.parse(localStorage.getItem(key)) || fallback; } catch { return fallback; } }
function save(key, value) { localStorage.setItem(key, JSON.stringify(value)); }
async function api(path, options = {}) { const response = await fetch(`/api/${path}`, { headers: { 'Content-Type': 'application/json' }, ...options }); if (!response.ok) { const error = await response.json().catch(() => ({})); throw new Error(error.error || 'Unable to connect to BloodCare server.'); } return response.json(); }
async function loadServerData() { try { [state.profiles, state.history] = await Promise.all([api('profiles'), api('history')]); renderProfiles(); } catch (error) { state.profiles = read(STORAGE.profiles, []); state.history = read(STORAGE.history, []); renderProfiles(); console.error(error); } }
function classify(systolic, diastolic) { if (systolic > 180 || diastolic > 120) return 'crisis'; if (systolic >= 140 || diastolic >= 90) return 'stage2'; if (systolic >= 130 || diastolic >= 80) return 'stage1'; if (systolic >= 120 && diastolic < 80) return 'elevated'; return 'normal'; }
function setTheme() { document.documentElement.dataset.theme = state.theme; localStorage.setItem(STORAGE.theme, state.theme); $('#theme-value').textContent = state.theme === 'dark' ? 'Dark' : 'Light'; document.querySelector('meta[name="theme-color"]').content = state.theme === 'dark' ? '#1a1a24' : '#f4f7fe'; }
function setLanguage() { document.documentElement.lang = state.language; localStorage.setItem(STORAGE.language, state.language); $('#language-value').textContent = state.language.toUpperCase(); document.querySelectorAll('[data-i18n]').forEach((node) => { node.textContent = copy[state.language][node.dataset.i18n]; }); }
function openDrawer(open) { $('#app-drawer').classList.toggle('open', open); $('#scrim').classList.toggle('visible', open); $('#app-drawer').setAttribute('aria-hidden', String(!open)); $('#menu-toggle').setAttribute('aria-expanded', String(open)); }
function renderProfiles() { if ($('#profile')) { const options = ['<option value="">Quick check — don\'t save</option>', ...state.profiles.map((profile) => `<option value="${profile.id}">${escapeHtml(profile.name)}</option>`)].join(''); $('#profile').innerHTML = options; } if ($('#history-filter')) { $('#history-filter').innerHTML = `<option value="all">All profiles</option>${state.profiles.map((profile) => `<option value="${profile.id}">${escapeHtml(profile.name)}</option>`).join('')}`; renderHistory(); } }
function renderHistory() { if (!$('#history-filter') || !$('#history-list')) return; const filter = $('#history-filter').value; const items = state.history.filter((entry) => filter === 'all' || entry.profileId === filter); $('#history-list').innerHTML = items.length ? items.map((entry) => `<article class="history-card"><div><strong>${escapeHtml(entry.profileName)}</strong><small>${entry.timestamp}</small></div><div class="history-reading">${entry.systolic} / ${entry.diastolic} mmHg<small>Pulse: ${entry.pulse || '—'} BPM</small></div><span class="history-badge" style="--badge:${categories[entry.category].color}">${categories[entry.category].label}</span></article>`).join('') : '<div class="empty-state"><span>🌱</span><p>Your saved check-ins will bloom here.</p></div>'; }
function showResult(entry) { const category = categories[entry.category]; const panel = $('#result-panel'); panel.hidden = false; panel.style.setProperty('--result-color', category.color); $('#result-title').textContent = category.title; $('#result-badge').textContent = category.label; $('#result-reading').textContent = `${entry.systolic} / ${entry.diastolic}`; $('#result-pulse').textContent = entry.pulse || '—'; $('#result-message').textContent = messages[entry.category === 'normal' ? 'normal' : entry.category === 'elevated' ? 'elevated' : 'high'][Math.floor(Math.random() * 3)]; $('#result-advice').textContent = entry.category === 'crisis' ? 'Please contact emergency medical services or a healthcare professional immediately.' : 'Keep checking in with yourself. One reading is a snapshot, not a diagnosis.'; $('#mascot-face').textContent = entry.category === 'normal' ? '◡' : '•ᴗ•'; panel.scrollIntoView({ behavior: 'smooth', block: 'nearest' }); }
function openProfile(profile = {}) { $('#profile-id').value = profile.id || ''; $('#profile-name').value = profile.name || ''; $('#profile-dob').value = profile.dob || ''; $('#dialog-title').textContent = profile.id ? 'Edit account' : 'Create account'; $('#profile-dialog').showModal(); }
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' })[char]); }
$('#menu-toggle').addEventListener('click', () => openDrawer(true)); $('#drawer-close').addEventListener('click', () => openDrawer(false)); $('#scrim').addEventListener('click', () => openDrawer(false));
document.querySelectorAll('[data-action]').forEach((button) => button.addEventListener('click', () => { const action = button.dataset.action; if (action === 'theme') { state.theme = state.theme === 'dark' ? 'light' : 'dark'; setTheme(); } else if (action === 'language') { state.language = state.language === 'en' ? 'id' : 'en'; setLanguage(); } else if (action === 'create-profile' || action === 'edit-profile') { if (!$('#profile-dialog')) { location.href = 'index.html'; return; } if (action === 'edit-profile' && state.profiles[0]) openProfile(state.profiles[0]); else openProfile(); } openDrawer(false); }));
if ($('#check-form')) $('#check-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const systolic = Number(form.get('systolic')); const diastolic = Number(form.get('diastolic')); const category = classify(systolic, diastolic); const profileId = form.get('profile'); const profile = state.profiles.find((item) => item.id === profileId); const entry = { systolic, diastolic, pulse: Number(form.get('pulse')) || '', category, profileId, profileName: profile ? profile.name : 'Quick check', timestamp: new Intl.DateTimeFormat(state.language === 'id' ? 'id-ID' : 'en-CA', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date()) }; showResult(entry); if (profile) { try { const savedEntry = await api('history', { method: 'POST', body: JSON.stringify(entry) }); state.history.unshift(savedEntry); } catch (error) { console.error(error); alert('The check was shown, but could not be saved to the server.'); } } });
if ($('#history-filter')) $('#history-filter').addEventListener('change', renderHistory);
if ($('#profile-form')) $('#profile-form').addEventListener('submit', async (event) => { event.preventDefault(); const id = $('#profile-id').value; const name = $('#profile-name').value.trim(); const dob = $('#profile-dob').value; if (!name) return; try { const profile = await api(id ? `profiles/${id}` : 'profiles', { method: id ? 'PUT' : 'POST', body: JSON.stringify({ name, dob }) }); const index = state.profiles.findIndex((item) => item.id === profile.id); if (index >= 0) state.profiles[index] = profile; else state.profiles.push(profile); renderProfiles(); $('#profile-dialog').close(); } catch (error) { $('#profile-name').setCustomValidity(error.message); $('#profile-name').reportValidity(); $('#profile-name').setCustomValidity(''); } });
setTheme(); setLanguage(); loadServerData();
